//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurSMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurSMSEntitiesNew2 : DbContext
    {
        public OurSMSEntitiesNew2()
            : base("name=OurSMSEntitiesNew2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Attendance> Attendances { get; set; }
        public DbSet<Classroom> Classrooms { get; set; }
        public DbSet<ClassroomType> ClassroomTypes { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Staff_User> Staff_User { get; set; }
        public DbSet<Student_Address> Student_Address { get; set; }
        public DbSet<Student_Tag> Student_Tag { get; set; }
        public DbSet<Student_tbl> Student_tbl { get; set; }
        public DbSet<StudentUser> StudentUsers { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<SubjectType> SubjectTypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WeeklySchedule> WeeklySchedules { get; set; }
        public DbSet<YearGroup> YearGroups { get; set; }
        public DbSet<Student_Subject> Student_Subject { get; set; }
        public DbSet<TimeSlot> TimeSlots { get; set; }
    }
}
