//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_tbl
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MobileNumber { get; set; }
        public string EmergencyContactNumber { get; set; }
        public Nullable<bool> Disability { get; set; }
        public string Notes { get; set; }
        public Nullable<int> YearGroup_ID { get; set; }
    }
}
