//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Address
    {
        public int StudentAddress_ID { get; set; }
        public int Student_ID { get; set; }
        public int Address_ID { get; set; }
    }
}
